export const reasons = [
    'Bo tak... i już',
    'jesteśmy nierozłączni',
    'zawsze przy mnie jesteś',
    'mocno się angażujesz w nasz związek',
    'zawsze o mnie myślisz',
    'uwielbiam z Tobą spędzać czas',
    'pokazujesz mi świat od innej perspektywy',
    'wiem że zawsze mogę na Ciebie liczyć',
    'pięknie wyglądasz',
    'starasz mi się podobać',
    'z nikim mi się tak dobrze nie ogląda seriali',
    'będziesz w przyszłości dobrą mamą',
    'nie czuję przy Tobie nudy',
    'znajdujesz nam zawsze dużo rozrywek',
    'jesteś tą jedyną',
    'dałaś mi w życiu wiele dobrego',
    'dajesz mi poczucie bliskości',
    'uwielbiam z Tobą chodzić na jedzenie',
    'kocham nasze wspólne wieczory',
    'nadajesz mojemu życiu sens',
    'w większości słuchasz tego co mówię :P',
    'głośno się śmiejesz',
    'nie miałem problemów z napisaniem tak wielu powodów dla których Cię kocham (to co właśnie widzisz)',
    'wiem że doceniasz to co dla Ciebie robię',
    'umiesz mnie pocieszyć',
    'jesteś powodem dla którego mi się po prostu chce',
    'mogę Ci wszystko powiedzieć',
    '(bonus) ogarniałem to po nocach żebyś miała niespodziankę więc jak są błędy to wybacz, ale kocham Cię mocno',
    'jesteś moją Kruszynką',
    'dzięki Tobie się otworzyłem',
    'twoje uczucia zawsze są szczere',
    'tylko ty mnie tak na prawdę rozumiesz',
    'radość daje mi patrzenie jak się z czegoś cieszysz',
    'zawsze mnie wspierasz',
    'jesteś mi wierna i oddana',
    'dobrze robisz wiesz co... :P',
    'dbasz o nasz dom',
    'nie przeszkadza Ci że mamy tylko siebie',
    'załatwiasz dużo spraw których ja nie potrafię',
    'kiedy poproszę robisz mi kawę której potrzebuje w pracy',
    'nie jesteś ze mną z przyzwyczajenia',
    'czuję że nie jesteś ze mną z jakiegoś błachego powodu jak np. pieniądze',
    'jesteś duszą towarzystwa',
    'nie chciałbym być z nikim innym',
    'jesteś wyjątkowa i niepowtarzalna',
    'mnie akceptujesz takim jakim jestes',
    'czuję że mogę być przy Tobie sobą',
    'dzięki Tobie mam z kim plotkować :D',
    'z Tobą u boku czuję że mogę podbić świat',
    'umiesz rozmawiać ze mna na trudne tematy',
    'mnie zaskakujesz',
    'dbasz o to żebym dobrze zarabiał :P',
    'jesteś powodem dla którego chciało mi się robić tą walentynkę'
]
